version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent connections
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root  # Gives Jenkins permission to access Docker
    restart: unless-stopped

volumes:
  jenkins_home:
